------------------------------------
-->> DATABASE EXPLORATION
------------------------------------

-- EXPLORE ALL OBJECTS IN DATABASE

SELECT * 
FROM INFORMATION_SCHEMA.TABLES  
ORDER BY TABLE_TYPE



-- EXPLORE ALL COLUMNS IN THE DATABASE

SELECT * 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'


-- DIMENSIONS EXPLORATION
-- TO UNDERSTAND THE GRANUALITY OF THE DIMENSION


-- EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM

SELECT 
  DISTINCT country 
FROM gold.dim_customers


-- EXPLORE ALL CATEGORIES THE MAJOR DIVISIONS

SELECT DISTINCT category,
  subcategory,
  product_name 
FROM gold.dim_products
ORDER BY 1,2


-- Find the First and Last Order date
-- How many years of sales available

SELECT 
  min(order_date) First_orderDate,
  max(order_date) AS Last_orderDate,
  DATEDIFF(MONTH,min(order_date),max(order_date)) AS Order_range_months
FROM gold.fact_sales


-- Find the oldest and youngest customer

SELECT 
  MIN(birth_date) Min_birth_date,
  DATEDIFF(Year,min(birth_date),GETDATE()) AS Oldest_age,
  MAX(birth_date) AS Max_birth_date,
  DATEDIFF(Year,MAX(birth_date),GETDATE()) AS Youngest_age
FROM gold.dim_customers







-- MEASURES EXPLORATION
-- CHECK THE BIG NUMBERS THAT MATTERS THE MOST TO OUR BUSINESS


-- Find the Total Sales
SELECT 
  SUM(sales_amount) AS Total_sales
FROM gold.fact_sales

-- Find how many items are sold
SELECT 
  SUM(quantity) AS Total_quantity
FROM gold.fact_sales

-- Find the average selling price
SELECT 
  AVG(price) AS Average_Price
FROM gold.fact_sales



-- Find the total number of orders
SELECT COUNT(order_number) AS Total_orders FROM gold.fact_sales        -- NOT CORRECT
SELECT COUNT(DISTINCT order_number) AS Total_orders FROM gold.fact_sales


-- Find the Total Number Of Products
SELECT COUNT(product_name) AS Total_products FROM gold.dim_products;
SELECT COUNT(DISTINCT product_id) AS Total_products FROM gold.dim_products;



-- Find the Total Number of Customers
SELECT COUNT(DISTINCT customer_key) FROM gold.dim_customers

-- Find total number of customers that has plced an order
SELECT COUNT(DISTINCT customer_key) FROM gold.fact_sales



-- Generate a Report that Shows all key metrics of the business

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION
SELECT 'Total Quantity', SUM(quantity) FROM gold.fact_sales
UNION
SELECT 'Average Price', AVG(price) FROM gold.fact_sales
UNION
SELECT 'Total No. Orders', COUNT(DISTINCT order_number) AS Total_orders FROM gold.fact_sales
UNION
SELECT 'Total No. Products', COUNT(product_name) FROM gold.dim_products
UNION
SELECT 'Total No. Customers', COUNT(customer_key) FROM gold.dim_customers





-- MAGNITUDE ANALYSIS

-- Find the Total Customers by Countries

SELECT 
  country,
  COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC


-- Find Total Customers by gender

SELECT 
  gender,
  COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC


-- Find Total products by category

SELECT 
  category,
  COUNT(product_key) as total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC


-- What is the Average Cost in each category

SELECT
  category, 
  AVG(cost) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

 
 -- What is the Total Revenue generated for each category

SELECT 
  p.category,
  SUM(s.sales_amount) AS totalrevenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY totalrevenue DESC


-- Find total revenue is generated by each customer

SELECT 
  c.customer_key,
  c.first_name,
  SUM(s.sales_amount) AS totalrevenue
FROM gold.fact_sales s
JOIN gold.dim_customers c
ON   s.customer_key = c.customer_key
GROUP BY c.customer_key,c.first_name
ORDER BY totalrevenue DESC


-- What is the distribution of sold items across countries

SELECT 
  c.country,
  SUM(s.quantity) AS total_distribution
FROM gold.fact_sales s
LEFT JOIN 
gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_distribution DESC




-- RANKING ANALYSIS

-- Order the values of dimension by measures

-- Which 5 products generate the highest revenue

SELECT TOP 5
  p.product_name, 
  SUM(s.sales_amount) AS totalsales
FROM gold.fact_sales s
LEFT JOIN
gold.dim_products p
ON s.product_key  = p.product_key
GROUP BY p.product_name
ORDER BY totalsales DESC


-- by window function
  
SELECT * 
FROM (SELECT
    		p.product_name, 
    		SUM(s.sales_amount) AS totalsales,
    		DENSE_RANK() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rank_products
  		FROM gold.fact_sales s
  		LEFT JOIN
  		gold.dim_products p
  		ON s.product_key  = p.product_key
  		GROUP BY p.product_name)t
WHERE rank_products <=5


-- What are the 5 worst performing products in terms of sales

SELECT TOP 5
  p.product_name, 
  SUM(s.sales_amount) AS totalsales
FROM gold.fact_sales s
LEFT JOIN
gold.dim_products p
ON s.product_key  = p.product_key
GROUP BY p.product_name
ORDER BY totalsales ASC



-- Find the top 10 customers who have generated the highest revenue

SELECT TOP 10
  c.customer_key,
  c.first_name,
  c.last_name,
  SUM(s.sales_amount) AS totalrevenue
FROM  gold.fact_sales s
left join gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY 
  c.customer_key,
  c.first_name,
  c.last_name
ORDER BY totalrevenue DESC

select 
  distinct customer_key,first_name,last_name 
from gold.dim_customers
order by first_name,last_name


-- 3 Customers with the fewest orders placed

SELECT TOP 3
  c.customer_key,
  c.first_name,
  c.last_name,
  COUNT(DISTINCT s.order_number) AS totalorders
FROM  gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON c.customer_key = s.customer_key
GROUP BY
  c.customer_key,
  c.first_name,
  c.last_name
ORDER BY totalorders 


